import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from 'next/link';
import { HeaderPage } from "@/src/components/header/header-page";
import { HomePage } from "@/src/components/home/home-page";
import { FooterPage } from "@/src/components/footer/footer-page";


const inter = Inter({ subsets: ["latin"] });

export default function Home({ data }) {
	return (
		<div>
			<Head>
				<title>Events App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<HomePage data={data} />
		</div>
	);
}

export async function getServerSideProps() {
	// const data = await import("/data/data.json")
	// console.log(data);

	const { events_categories } = await import("/data/data.json");

	return {
		props: {
			data: events_categories,
		},
	};
}
